# -*- coding: utf-8 -*-
"""RF_SENTIENL_CL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15i6DXM3_uqRkCWqq-AtRmMylTfnZT7_a
"""

# -*- coding: utf-8 -*-
"""
rf_sentinel_v4.py
=================
Google Earth Engine extraction script for forest health modeling
(ME / NH / VT — 154 plots).

Changes over v3:
  - LandTrendr removed entirely
  - Export to Google Drive (replaces .getInfo() which hit memory limits)

Data sources:
  Sentinel-2 SR  : COPERNICUS/S2_SR_HARMONIZED             (10/20m, 2023+2024)
  Sentinel-1 GRD : COPERNICUS/S1_GRD                       (10m, ASC, 2023+2024)
  GEDI L2A       : LARSE/GEDI/GEDI02_A_002_MONTHLY         (25m, 2019–2024 mean)
  NLCD TCC       : USGS/NLCD_RELEASES/2023_REL/TCC/v2023-5 (30m, static)
  Terrain        : USGS/3DEP/10m_collection                 (10m, static)

Author : (your name)
Project: Forest Health Index — ME / NH / VT
"""

# ============================================================
# 0. INSTALL & AUTHENTICATE
# ============================================================
# Run once in Colab:
# !pip install geemap rasterio scikit-learn geopandas pandas pyproj openpyxl

import ee
import geemap
import geopandas as gpd
import pandas as pd
import numpy as np
import time

ee.Authenticate()
ee.Initialize(project='ee-garimayadav')

# ============================================================
# 1. LOAD FIELD DATA & BUILD GEODATAFRAME
# ============================================================
FILE_PATH = '/content/feild_data_latest_corrected.xlsx'

field_df = pd.read_excel(FILE_PATH, sheet_name='feild_data_latest_corrected')
field_df = field_df.dropna(subset=['X', 'Y', 'ID', 'Date'])
field_df['Date']       = pd.to_datetime(field_df['Date'])
field_df['visit_year'] = field_df['Date'].dt.year
field_df['Strand']     = field_df['Strand'].replace(0, 'mixed')   # fix data entry error

def make_gdf(df, epsg):
    return gpd.GeoDataFrame(
        df,
        geometry=gpd.points_from_xy(df['X'], df['Y']),
        crs=f"EPSG:{epsg}"
    ).to_crs(epsg=4326)

vt_gdf       = make_gdf(field_df[field_df['State'] == 'VT'],            32618)
me_nh_gdf    = make_gdf(field_df[field_df['State'].isin(['ME','NH'])],   32619)
combined_gdf = pd.concat([vt_gdf, me_nh_gdf]).reset_index(drop=True)

print(f"Plots loaded : {len(combined_gdf)}")
print(f"  2023 plots : {(combined_gdf['visit_year']==2023).sum()}")
print(f"  2024 plots : {(combined_gdf['visit_year']==2024).sum()}")

# ============================================================
# 2. GEE REGION OF INTEREST
# ============================================================
states = ee.FeatureCollection("TIGER/2018/States")
combined_region = (
    states.filter(ee.Filter.eq("NAME", "Vermont"))
          .merge(states.filter(ee.Filter.eq("NAME", "Maine")))
          .merge(states.filter(ee.Filter.eq("NAME", "New Hampshire")))
)

# ============================================================
# 3. PHENOLOGICAL WINDOWS (Apr–Nov, extended for cloud gaps)
# ============================================================
MONTH_WINDOWS = {
    "Apr": ("04-01", "04-30"),
    "May": ("04-25", "06-05"),
    "Jun": ("05-25", "07-08"),
    "Jul": ("06-25", "07-31"),
    "Aug": ("07-27", "09-04"),
    "Sep": ("09-01", "09-30"),
    "Oct": ("09-24", "11-05"),
    "Nov": ("10-25", "12-05"),
}

def make_date_ranges(year):
    return {m: (f"{year}-{s}", f"{year}-{e}")
            for m, (s, e) in MONTH_WINDOWS.items()}

DATE_RANGES_2023 = make_date_ranges(2023)
DATE_RANGES_2024 = make_date_ranges(2024)

# ============================================================
# 4. SENTINEL-2 — CLOUD MASKING (SCL only, no band thresholds)
# ============================================================
def mask_s2_clouds_scl(image):
    """
    Mask using SCL only:
      3  = cloud shadow
      8  = cloud medium probability
      9  = cloud high probability
      10 = cirrus
    Scale reflectance from DN (0-10000) to 0-1.
    """
    scl  = image.select('SCL')
    mask = (scl.neq(3)
               .And(scl.neq(8))
               .And(scl.neq(9))
               .And(scl.neq(10)))
    return image.updateMask(mask).divide(10000)

# ============================================================
# 5. SENTINEL-2 — SPECTRAL INDICES + RAW BANDS
# ============================================================
def calculate_indices(image):
    """
    25 spectral indices across Structure / Physiology / Biochemistry.
    Raw bands B2-B8A, B11, B12 retained automatically via image.addBands.
    All NIR references use B8A (narrow NIR, 20m).
    """
    # --- STRUCTURE ---
    NDVI  = image.expression('(NIR-RED)/(NIR+RED)',
              {'NIR':image.select('B8A'),'RED':image.select('B4')}).rename('NDVI')
    ARVI  = image.expression('(NIR-(2*RED-BLUE))/(NIR+(2*RED-BLUE))',
              {'NIR':image.select('B8A'),'RED':image.select('B4'),
               'BLUE':image.select('B2')}).rename('ARVI')
    EVI7  = image.expression('2.5*(RE3-RED)/(1+RE3+6*RED-7.5*BLUE)',
              {'RE3':image.select('B7'),'RED':image.select('B4'),
               'BLUE':image.select('B2')}).rename('EVI7')
    EVI8  = image.expression('2.5*(NIR-RED)/(1+NIR+6*RED-7.5*BLUE)',
              {'NIR':image.select('B8A'),'RED':image.select('B4'),
               'BLUE':image.select('B2')}).rename('EVI8')
    MSR   = image.expression('((RE3/RED)-1)/sqrt((RE3/RED)+1)',
              {'RE3':image.select('B7'),'RED':image.select('B4')}).rename('MSR')
    SAVI  = image.expression('1.5*(NIR-RED)/(NIR+RED+0.5)',
              {'NIR':image.select('B8A'),'RED':image.select('B4')}).rename('SAVI')
    WDRVI = image.expression('((0.01*RE3)-RED)/((0.01*RE3)+RED+0.98)',
              {'RE3':image.select('B7'),'RED':image.select('B4')}).rename('WDRVI')

    # --- PHYSIOLOGY / STRESS ---
    ARI1  = image.expression('(1/GREEN)-(1/RE1)',
              {'GREEN':image.select('B3'),'RE1':image.select('B5')}).rename('ARI1')
    ARI2  = image.expression('(NIR/GREEN)-(NIR/RE1)',
              {'NIR':image.select('B8A'),'GREEN':image.select('B3'),
               'RE1':image.select('B5')}).rename('ARI2')
    CRI1  = image.expression('(1/BLUE)-(1/GREEN)',
              {'BLUE':image.select('B2'),'GREEN':image.select('B3')}).rename('CRI1')
    CRI2  = image.expression('(1/BLUE)-(1/RE1)',
              {'BLUE':image.select('B2'),'RE1':image.select('B5')}).rename('CRI2')
    NDII11= image.expression('(NIR-SWIR1)/(NIR+SWIR1)',
              {'NIR':image.select('B8A'),'SWIR1':image.select('B11')}).rename('NDII11')
    NDII12= image.expression('(NIR-SWIR2)/(NIR+SWIR2)',
              {'NIR':image.select('B8A'),'SWIR2':image.select('B12')}).rename('NDII12')
    PSRI  = image.expression('(RED-GREEN)/NIR',
              {'RED':image.select('B4'),'GREEN':image.select('B3'),
               'NIR':image.select('B8A')}).rename('PSRI')

    # --- CHLOROPHYLL / BIOCHEMISTRY ---
    GCI   = image.expression('(NIR/GREEN)-1',
              {'NIR':image.select('B8A'),'GREEN':image.select('B3')}).rename('GCI')
    Clre  = image.expression('(RE3/RE1)-1',
              {'RE3':image.select('B7'),'RE1':image.select('B5')}).rename('Clre')
    GARI  = image.expression(
              '((NIR-GREEN)-(BLUE-RED))/((NIR+GREEN)-(BLUE-RED))',
              {'NIR':image.select('B8A'),'GREEN':image.select('B3'),
               'BLUE':image.select('B2'),'RED':image.select('B4')}).rename('GARI')
    GNDVI = image.expression('(NIR-GREEN)/(NIR+GREEN)',
              {'NIR':image.select('B8A'),'GREEN':image.select('B3')}).rename('GNDVI')
    IRECI = image.expression('(RE2/RE1)*(RE3-RED)',
              {'RE2':image.select('B6'),'RE1':image.select('B5'),
               'RE3':image.select('B7'),'RED':image.select('B4')}).rename('IRECI')
    MCARI = image.expression('1-(0.2*(RE1-GREEN)/(RE1-RED))',
              {'RE1':image.select('B5'),'GREEN':image.select('B3'),
               'RED':image.select('B4')}).rename('MCARI')
    TCARI = image.expression('3*(RE1-RED)-0.2*(RE1-GREEN)*(RE1/RED)',
              {'RE1':image.select('B5'),'RED':image.select('B4'),
               'GREEN':image.select('B3')}).rename('TCARI')
    NDVIRE= image.expression('(NIR-RE2)/(NIR+RE2)',
              {'NIR':image.select('B8A'),'RE2':image.select('B6')}).rename('NDVIRE')
    NDI45 = image.expression('(RE1-RED)/(RE1+RED)',
              {'RE1':image.select('B5'),'RED':image.select('B4')}).rename('NDI45')
    S2REP = image.expression('705+35*((((RE3+RED)/2)-RE1)/(RE2-RE1))',
              {'RE3':image.select('B7'),'RE2':image.select('B6'),
               'RE1':image.select('B5'),'RED':image.select('B4')}).rename('S2REP')
    TVI   = image.expression('0.5*(120*(RE2-GREEN)-200*(RED-GREEN))',
              {'RE2':image.select('B6'),'RED':image.select('B4'),
               'GREEN':image.select('B3')}).rename('TVI')

    return image.addBands([
        NDVI, ARVI, EVI7, EVI8, MSR, SAVI, WDRVI,
        ARI1, ARI2, CRI1, CRI2, NDII11, NDII12, PSRI,
        GCI, Clre, GARI, GNDVI, IRECI, MCARI, TCARI,
        NDVIRE, NDI45, S2REP, TVI
    ])

# ============================================================
# 6. SENTINEL-2 — BUILD MONTHLY COMPOSITES
# ============================================================
def build_s2_composites(date_ranges):
    composites = {}
    for month, (start, end) in date_ranges.items():
        col = (ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
               .filterDate(start, end)
               .filterBounds(combined_region)
               .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 40))
               .select(['B2','B3','B4','B5','B6','B7','B8','B8A','B11','B12','SCL'])
               .map(mask_s2_clouds_scl)
               .map(calculate_indices))
        n = col.size().getInfo()
        if n == 0:
            print(f"  [WARN] No S2 for {month} ({start}–{end})")
            composites[month] = None
        else:
            composites[month] = col.median().clip(combined_region)
            print(f"  [OK] S2 {month} ({start}–{end}): {n} scenes")
    return composites

print("Building 2023 S2 composites...")
s2_composites_2023 = build_s2_composites(DATE_RANGES_2023)
print("Building 2024 S2 composites...")
s2_composites_2024 = build_s2_composites(DATE_RANGES_2024)

# ============================================================
# 7. SENTINEL-1 — BACKSCATTER + GLCM TEXTURES
# ============================================================
def preprocess_s1(date_range):
    """
    ASC-only median composite in dB.
    Derived dB metrics:
        VV_VH_Ratio = VV - VH
        Sqrt_VV_VH  = (VV-VH)/2
        VV_Times_VH = VV + VH
    GLCM textures on VV (window size=3):
        ASM, contrast, correlation, variance, homogeneity (IDM), entropy
    """
    s1_col = (ee.ImageCollection('COPERNICUS/S1_GRD')
              .filterDate(date_range[0], date_range[1])
              .filterBounds(combined_region)
              .filter(ee.Filter.eq('instrumentMode', 'IW'))
              .filter(ee.Filter.eq('orbitProperties_pass', 'ASCENDING'))
              .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
              .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'))
              .select(['VV', 'VH']))

    if s1_col.size().getInfo() == 0:
        print(f"  [WARN] No S1 ASC for {date_range}")
        return None

    composite   = s1_col.median().clip(combined_region)
    vv          = composite.select('VV')
    vh          = composite.select('VH')

    vv_vh_ratio = vv.subtract(vh).rename('VV_VH_Ratio')
    sqrt_vv_vh  = vv.subtract(vh).divide(2).rename('Sqrt_VV_VH')
    vv_times_vh = vv.add(vh).rename('VV_Times_VH')

    # GLCM: scale VV from dB (~-25 to 0) → 0-255 int required by glcmTexture
    vv_scaled = (vv.unitScale(-25, 0)
                   .multiply(255)
                   .toInt()
                   .rename('VV_scaled'))
    glcm = vv_scaled.glcmTexture(size=3).select([
        'VV_scaled_asm',
        'VV_scaled_contrast',
        'VV_scaled_corr',
        'VV_scaled_var',
        'VV_scaled_idm',
        'VV_scaled_ent',
    ])

    return (composite
            .addBands(vv_vh_ratio)
            .addBands(sqrt_vv_vh)
            .addBands(vv_times_vh)
            .addBands(glcm))

def build_s1_composites(date_ranges):
    composites = {}
    for month, date_range in date_ranges.items():
        print(f"  Processing S1 {month}...")
        composites[month] = preprocess_s1(date_range)
    return composites

print("Building 2023 S1 composites...")
s1_composites_2023 = build_s1_composites(DATE_RANGES_2023)
print("Building 2024 S1 composites...")
s1_composites_2024 = build_s1_composites(DATE_RANGES_2024)

# ============================================================
# 8. TERRAIN — ELEVATION + SLOPE + ASPECT (USGS 3DEP 10m)
# ============================================================
dem = ee.ImageCollection("USGS/3DEP/10m_collection").mosaic()

terrain_image = (
    dem.rename('elevation_10m')
       .addBands(ee.Terrain.slope(dem).rename('slope_10m'))
       .addBands(ee.Terrain.aspect(dem).rename('aspect_10m'))
)

# ============================================================
# 9. GEDI L2A — CANOPY HEIGHT & COVER
# ============================================================
gedi = (ee.ImageCollection('LARSE/GEDI/GEDI02_A_002_MONTHLY')
        .filterBounds(combined_region)
        .filterDate('2019-01-01', '2024-12-31')
        .map(lambda img: img.updateMask(
             img.select('quality_flag').eq(1)
                .And(img.select('degrade_flag').eq(0))))
        .select(['rh50', 'rh75', 'rh98', 'landsat_treecover'])
        .mean()
        .clip(combined_region)
        .rename(['GEDI_rh50', 'GEDI_rh75', 'GEDI_rh98', 'GEDI_cover']))

print("GEDI image prepared.")

# ============================================================
# 10. NLCD 2023 — PERCENT TREE CANOPY COVER
# ============================================================
nlcd_canopy = (ee.ImageCollection('USGS/NLCD_RELEASES/2023_REL/TCC/v2023-5')
               .first()
               .select('NLCD_Percent_Tree_Canopy_Cover')
               .rename('NLCD_canopy_pct')
               .clip(combined_region))

print("NLCD canopy cover image prepared.")

# ============================================================
# 11. BUILD EE FEATURE COLLECTION (once)
# ============================================================
ee_features = []
for _, row in combined_gdf.iterrows():
    feat = ee.Feature(
        ee.Geometry.Point([row.geometry.x, row.geometry.y]),
        {
            'ID':         int(row['ID']),
            'Plot_no':    row['Plot_no'],
            'State':      row['State'],
            'Sites':      row['Sites'],
            'X':          row['X'],
            'Y':          row['Y'],
            'visit_year': int(row['visit_year']),
        }
    )
    ee_features.append(feat)

central_points_ee = ee.FeatureCollection(ee_features)
print(f"EE FeatureCollection: {central_points_ee.size().getInfo()} features")

# ============================================================
# 12. EXTRACTION HELPERS
# ============================================================
def extract_point(feature, image, prefix):
    """Extract all bands at point, prefix band names with month_year."""
    values   = image.reduceRegion(
                   reducer=ee.Reducer.first(),
                   geometry=feature.geometry(),
                   scale=10,
                   maxPixels=1e9)
    keys     = values.keys()
    new_keys = keys.map(lambda k: ee.String(k).cat('_').cat(prefix))
    return feature.set(ee.Dictionary.fromLists(new_keys, values.values(keys)))


def make_extractor(image, scale):
    """
    Closure factory — returns single-argument function for .map().
    No prefix; static layers use their own band names as-is.
    """
    def _extract(feature):
        values = image.reduceRegion(
                     reducer=ee.Reducer.first(),
                     geometry=feature.geometry(),
                     scale=scale,
                     maxPixels=1e9)
        return feature.set(values)
    return _extract


# Pre-built extractors for static layers
extract_terrain_fn = make_extractor(terrain_image, scale=10)
extract_nlcd_fn    = make_extractor(nlcd_canopy,   scale=30)

def extract_gedi_buffered(feature):
    """
    GEDI has sparse orbital coverage — a point extractor returns null
    for most plots. Buffer 500m and take mean of any shots within range.
    If still null (no shots within 500m), returns null gracefully.
    """
    buffered = feature.geometry().buffer(500)
    values   = gedi.reduceRegion(
                   reducer=ee.Reducer.mean(),
                   geometry=buffered,
                   scale=25,
                   maxPixels=1e9)
    return feature.set(values)

# ============================================================
# 13. EXTRACT S2 — PER-PLOT YEAR MATCHING
# ============================================================
print("\nExtracting Sentinel-2 (indices + raw bands)...")

for year, s2_composites in [(2023, s2_composites_2023),
                             (2024, s2_composites_2024)]:
    year_fc = central_points_ee.filter(ee.Filter.eq('visit_year', year))
    n = year_fc.size().getInfo()
    print(f"  Year {year}: {n} plots")
    if n == 0:
        continue
    for month, composite in s2_composites.items():
        if composite is None:
            print(f"    [SKIP] S2 {month} {year}")
            continue
        year_fc = year_fc.map(
            lambda f, c=composite, m=month: extract_point(f, c, m))
    if year == 2023:
        s2_fc_2023 = year_fc
    else:
        s2_fc_2024 = year_fc

s2_fc_all = s2_fc_2023.merge(s2_fc_2024)
print("S2 extraction complete.")

# ============================================================
# 14. EXTRACT S1 — PER-PLOT YEAR MATCHING
# ============================================================
print("\nExtracting Sentinel-1 (backscatter + GLCM textures)...")

for year, s1_composites in [(2023, s1_composites_2023),
                             (2024, s1_composites_2024)]:
    year_fc = s2_fc_all.filter(ee.Filter.eq('visit_year', year))
    n = year_fc.size().getInfo()
    if n == 0:
        continue
    for month, composite in s1_composites.items():
        if composite is None:
            print(f"    [SKIP] S1 {month} {year}")
            continue
        year_fc = year_fc.map(
            lambda f, c=composite, m=month: extract_point(f, c, f"S1_{m}"))
    if year == 2023:
        s1_fc_2023 = year_fc
    else:
        s1_fc_2024 = year_fc

s1_fc_all = s1_fc_2023.merge(s1_fc_2024)
print("S1 extraction complete.")

# ============================================================
# 15. EXTRACT STATIC LAYERS
# ============================================================
print("\nExtracting terrain (elevation, slope, aspect)...")
fc_terrain = s1_fc_all.map(extract_terrain_fn)

print("Extracting GEDI canopy height...")
fc_gedi    = fc_terrain.map(extract_gedi_fn)

print("Extracting NLCD canopy cover...")
fc_final   = fc_gedi.map(extract_nlcd_fn)

print("All static extractions complete.")

# ============================================================
# 16. EXPORT TO GOOGLE DRIVE
# ============================================================
# .getInfo() exceeds GEE memory limits for large feature collections.
# Export to Drive runs server-side with no memory cap.
# Download the CSV from Drive then run section 17b onwards.

task = ee.batch.Export.table.toDrive(
    collection=fc_final,
    description='forest_indices_v4',
    folder='GEE_exports',            # created automatically in your Drive
    fileNamePrefix='forest_indices_v4',
    fileFormat='CSV'
)
task.start()
print("\nExport task started!")
print("Monitor at: https://code.earthengine.google.com/tasks")
print("Typical duration: 5–15 minutes for 154 plots.")
print("Once complete, download the CSV from Drive/GEE_exports/ and run section 17b.")

# Optional: poll until complete (comment out if you prefer manual check)
print("\nWaiting for export...")
while task.active():
    status = task.status()['state']
    print(f"  Status: {status}")
    time.sleep(30)
print(f"  Final status: {task.status()['state']}")

# ============================================================
# 17b. LOAD EXPORTED CSV
# ============================================================
# After downloading from Google Drive, update the path below and run from here.

CSV_PATH = '/content/forest_indices_v5.xlsx'   # update if needed
df_raw   = pd.read_excel(CSV_PATH)
print(f"\nLoaded: {df_raw.shape[0]} rows × {df_raw.shape[1]} cols")

# ============================================================
# 18. SEASONAL AMPLITUDE FEATURES (client-side)
# ============================================================
print("Computing seasonal amplitude features...")

MONTHS  = list(MONTH_WINDOWS.keys())
INDICES = ['NDVI', 'EVI8', 'GNDVI', 'NDII11', 'S2REP',
           'IRECI', 'PSRI', 'SAVI']

amplitude_rows = []

for _, row in df_raw.iterrows():
    year = int(row['visit_year'])
    amp  = {}

    for idx in INDICES:
        monthly_vals = []
        for m in MONTHS:
            col = f"{idx}_{m}"
            if col in row and pd.notna(row[col]):
                monthly_vals.append((m, float(row[col])))

        if len(monthly_vals) >= 3:
            vals = [v for _, v in monthly_vals]
            amp[f'{idx}_season_max']  = max(vals)
            amp[f'{idx}_season_min']  = min(vals)
            amp[f'{idx}_season_amp']  = max(vals) - min(vals)
            amp[f'{idx}_season_mean'] = float(np.mean(vals))
            amp[f'{idx}_peak_month']  = monthly_vals[vals.index(max(vals))][0]
        else:
            for s in ['season_max','season_min','season_amp','season_mean','peak_month']:
                amp[f'{idx}_{s}'] = None

    # NDVI green-up rate (Apr→Jun slope)
    early = [float(row[f'NDVI_{m}']) for m in ['Apr','May','Jun']
             if f'NDVI_{m}' in row and pd.notna(row[f'NDVI_{m}'])]
    amp['NDVI_greenup_rate'] = (early[-1]-early[0])/len(early) if len(early)>=2 else None

    # NDVI senescence rate (Aug→Nov slope)
    late = [float(row[f'NDVI_{m}']) for m in ['Aug','Sep','Oct','Nov']
            if f'NDVI_{m}' in row and pd.notna(row[f'NDVI_{m}'])]
    amp['NDVI_senescence_rate'] = (late[-1]-late[0])/len(late) if len(late)>=2 else None

    amplitude_rows.append(amp)

df_amp = pd.DataFrame(amplitude_rows)
df_raw = pd.concat([df_raw.reset_index(drop=True),
                    df_amp.reset_index(drop=True)], axis=1)

print(f"  Added {df_amp.shape[1]} seasonal amplitude features.")

# ============================================================
# 19. MERGE WITH FIELD OBSERVATIONS
# ============================================================
field_obs = field_df[['ID','LAI','LCR100','Tree_Count',
                       'Canopy_Height','Strand','visit_year']].copy()
field_obs['ID'] = field_obs['ID'].astype(int)
df_raw['ID']    = df_raw['ID'].astype(int)

final_df = pd.merge(df_raw, field_obs, on='ID', how='inner',
                    suffixes=('', '_field'))

print(f"\nFinal DataFrame: {final_df.shape[0]} plots × {final_df.shape[1]} features")

# ============================================================
# 20. EXPORT TO EXCEL (4 sheets)
# ============================================================
OUTPUT_FILE = 'forest_indices_v4.xlsx'

amp_cols = [c for c in final_df.columns if any(x in c for x in
            ['season_','peak_month','greenup','senescence'])]

static_cols = ['ID','State','visit_year',
               'elevation_10m','slope_10m','aspect_10m',
               'GEDI_rh50','GEDI_rh75','GEDI_rh98','GEDI_cover',
               'NLCD_canopy_pct']
static_present = [c for c in static_cols if c in final_df.columns]

with pd.ExcelWriter(OUTPUT_FILE, engine='openpyxl', mode='w') as writer:

    final_df.to_excel(writer, sheet_name='All_Data', index=False)

    id_cols = ['ID','State','Sites','visit_year',
               'LAI','LCR100','Tree_Count','Canopy_Height']
    final_df[id_cols + amp_cols].to_excel(
        writer, sheet_name='Amplitude_Features', index=False)

    final_df[static_present].to_excel(
        writer, sheet_name='Static_Variables', index=False)

    qa = final_df.isnull().sum().reset_index()
    qa.columns = ['Feature','Null_Count']
    qa['Null_Pct'] = (qa['Null_Count'] / len(final_df) * 100).round(2)
    qa[qa['Null_Count'] > 0].sort_values('Null_Count', ascending=False).to_excel(
        writer, sheet_name='QA_Null_Summary', index=False)

print(f"\nExported → {OUTPUT_FILE}")
print(f"  All_Data          : {final_df.shape[0]} rows × {final_df.shape[1]} cols")
print(f"  Amplitude_Features: {len(amp_cols)} seasonal features")
print(f"  Static_Variables  : {len(static_present)} static features")
print(f"  QA_Null_Summary   : missing value audit")

# ============================================================
# FEATURE INVENTORY
# ============================================================
s1_cols = [c for c in final_df.columns if c.startswith('S1_')]
print("\n" + "="*55)
print("FEATURE INVENTORY")
print("="*55)
print(f"  S2 indices + raw bands : {len([c for c in final_df.columns if any(f'_{m}_' in c for m in MONTHS) and not c.startswith('S1_')])} cols")
print(f"  S1 backscatter + GLCM  : {len(s1_cols)} cols")
print(f"  Seasonal amplitude     : {len(amp_cols)} cols")
print(f"  Static layers          : {len(static_present)} cols")
print(f"  Total                  : {final_df.shape[1]} cols")
print("="*55)

